// frontend/src/components/social_media/SocialMedia.tsx
import React from "react";

import { ReactComponent as MediumIcon } from "../../assets/medium_icon.svg";
import { ReactComponent as LinkedinAndInstagramIcons } from "../../assets/linkedin_and_insta_icons.svg";


const SocialMedia = () => {
  return (
    <>
      <a href='https://medium.com/@bitwisetechnology' target='_blank' rel='noreferrer'>
        <MediumIcon />
      </a>
      <a href='https://www.instagram.com/bitwisetechnology/' target='_blank' rel='noreferrer'>
        {" "}
        <LinkedinAndInstagramIcons />
      </a>
    </>
  );
};

export default SocialMedia;

// src/components/SocialMedia.vue
<template lang="pug">
  .media
    .medium
      a(
        href="https://medium.com/"
        target="_blank"
        )
        img(src="../assets/Medium.svg")
    .linkedin
      a(
        href="https://www.linkedin.com/company/bitwisetechnology/"
        target="_blank"
      )
        i.fab.fa-linkedin
    .instagram
      a(
        href="https://www.linkedin.com/company/bitwisetechnology/"
        target="_blank"
      )
        i.fab.fa-instagram
</template>

<script>

export default {
  name: 'social-media'
}
</script>

<style lang="scss" scoped>
.media {
  display: grid;
  grid-template-columns: auto auto auto;
  column-gap: 12px;
  i {
    color: #FD71EA;
    font-size: 28px;
  }
}
</style>
